### ISSUE TITLE
Data Cleansing

### ISSUE THREAD

**Issue by Jfbarr** [Jfbarr/aus_open_datathon_2019#3]
Need to perform some cleansing on the data supplied. Datatypes need to be consistent (ints stored as ints not strings), missing values entered (set to 0 or set to mean/some other method), etc. 

For example, one record has Winner_SecondServes_Won with ".", causing the column to be stored as a string datatype. When "np.sum" is applied to the column, this will just concatenate the strings so that 18 + 35 becomes "1835".

**Comment by Jfbarr** [comment]
Added labels

**Comment by XDynames** [comment]
I believe I have resolved this in the new branch DataCleaning. I didn't see a reason to fill any variables with the average as most are discrete integers where a missing value is reasonably interpreted as 0. I have retained missing values in the winner/loser rank variables as I believe this means they do not have a rank? Correct me if I am wrong there

**Comment by Jfbarr** [comment]
I agree with all your points, good stuff 👍
